-- Generated from packages/spec/controls.json. Do not edit by hand.
return {
    Widget = { name = "控件", ui = "Widget", category = "基础", children = false, bindable = nil, events = {  } },
    Panel = { name = "容器", ui = "Panel", category = "基础", children = true, bindable = nil, events = {  } },
    TextField = { name = "文本框", ui = "TextField", category = "输入", children = false, bindable = "Text", events = { "Change", "Submit", "Focus", "Blur" } },
    Checkbox = { name = "复选框", ui = "Checkbox", category = "输入", children = false, bindable = "Value", events = { "Change" } },
    Dropdown = { name = "下拉框", ui = "Dropdown", category = "输入", children = false, bindable = "Value", events = { "Change", "Open", "Close" } },
    Toast = { name = "吐司", ui = "Toast", category = "反馈", children = false, bindable = nil, events = { "Close" } },
    Tabs = { name = "选项卡", ui = "Tabs", category = "导航", children = false, bindable = "Value", events = { "Change" } },
    Tooltip = { name = "工具提示", ui = "Tooltip", category = "反馈", children = true, bindable = nil, events = {  } },
    Badge = { name = "徽章", ui = "Badge", category = "展示", children = false, bindable = nil, events = {  } },
    Avatar = { name = "头像", ui = "Avatar", category = "展示", children = false, bindable = nil, events = {  } },
    List = { name = "列表", ui = "List", category = "数据", children = true, bindable = nil, events = { "Select" } },
    Divider = { name = "分隔线", ui = "Divider", category = "布局", children = false, bindable = nil, events = {  } },
    Skeleton = { name = "骨架屏", ui = "Skeleton", category = "反馈", children = false, bindable = nil, events = {  } },
    Chip = { name = "标签片", ui = "Chip", category = "输入", children = false, bindable = "Value", events = { "Click", "Change" } },
    Accordion = { name = "折叠面板", ui = "Accordion", category = "布局", children = true, bindable = nil, events = { "Change" } },
    Stepper = { name = "步骤条", ui = "Stepper", category = "导航", children = false, bindable = "Value", events = { "Change" } },
    Rating = { name = "评分", ui = "Rating", category = "输入", children = false, bindable = "Value", events = { "Change" } },
    Breadcrumb = { name = "面包屑", ui = "Breadcrumb", category = "导航", children = false, bindable = nil, events = { "Select" } },
    Pagination = { name = "分页", ui = "Pagination", category = "导航", children = false, bindable = "Value", events = { "Change" } },
    Alert = { name = "警告框", ui = "Alert", category = "反馈", children = false, bindable = nil, events = { "Close" } },
    Timeline = { name = "时间线", ui = "Timeline", category = "数据", children = false, bindable = nil, events = {  } },
    Menu = { name = "菜单", ui = "Menu", category = "导航", children = false, bindable = nil, events = { "Select" } },
    Tree = { name = "树", ui = "Tree", category = "数据", children = false, bindable = nil, events = { "Select", "Change" } },
    DatePicker = { name = "日期选择器", ui = "DatePicker", category = "输入", children = false, bindable = "Value", events = { "Change" } },
    TimePicker = { name = "时间选择器", ui = "TimePicker", category = "输入", children = false, bindable = "Value", events = { "Change" } },
    ColorPicker = { name = "颜色选择器", ui = "ColorPicker", category = "输入", children = false, bindable = "Value", events = { "Change" } },
    Table = { name = "表格", ui = "Table", category = "数据", children = false, bindable = nil, events = { "Select" } },
    Carousel = { name = "轮播", ui = "Carousel", category = "导航", children = false, bindable = "Value", events = { "Change" } },
    Drawer = { name = "抽屉", ui = "Drawer", category = "反馈", children = true, bindable = nil, events = { "Open", "Close" } },
    Popover = { name = "弹出层", ui = "Popover", category = "反馈", children = true, bindable = nil, events = { "Open", "Close" } },
    Calendar = { name = "日历", ui = "Calendar", category = "输入", children = false, bindable = "Value", events = { "Change", "Select" } },
    FileUpload = { name = "文件上传", ui = "FileUpload", category = "输入", children = false, bindable = nil, events = { "Change", "Submit" } },
    RichText = { name = "富文本", ui = "RichText", category = "展示", children = false, bindable = nil, events = {  } },
    SimpleGrid = { name = "简单网格", ui = "SimpleGrid", category = "布局", children = true, bindable = nil, events = {  } },
    Spine = { name = "骨骼动画", ui = "Spine", category = "媒体", children = false, bindable = nil, events = { "Complete" } },
    SpriteSheet = { name = "精灵表", ui = "SpriteSheet", category = "媒体", children = false, bindable = nil, events = { "Complete" } },
    Sprite = { name = "精灵", ui = "Sprite", category = "媒体", children = false, bindable = nil, events = {  } },
    VirtualList = { name = "虚拟列表", ui = "VirtualList", category = "数据", children = false, bindable = nil, events = { "Select" } },
    DragDropContext = { name = "拖放上下文", ui = "DragDropContext", category = "交互", children = true, bindable = nil, events = { "DragStart", "DragEnd", "DragCancel" } },
    ItemSlot = { name = "物品槽", ui = "ItemSlot", category = "交互", children = false, bindable = nil, events = { "Click", "Change" } },
    SkillTree = { name = "技能树", ui = "SkillTree", category = "交互", children = false, bindable = nil, events = { "Select", "Change" } },
    ChatWindow = { name = "聊天窗口", ui = "ChatWindow", category = "组合", children = false, bindable = nil, events = { "Submit", "Select" } },
    ItemTooltip = { name = "物品提示", ui = "ItemTooltip", category = "组合", children = false, bindable = nil, events = {  } },
}
