import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("the LUI custom editor has one tag and does not create a native editor group", async () => {
  const host = await readFile("src/extension.ts", "utf8");
  const designer = await readFile("src/webview/designer.ts", "utf8");
  const html = await readFile("src/extension.ts", "utf8");
  const css = await readFile("media/preview.css", "utf8");
  assert.match(host, /supportsMultipleEditorsPerDocument:\s*false/);
  for (const forbidden of ["splitEditorDown", "focusSecondEditorGroup", "type:'reveal'", 'type: "reveal"']) assert.doesNotMatch(host, new RegExp(forbidden.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.match(host, /message.type === 'openProperty'/); // Native navigation is explicit declaration navigation only.
  assert.match(host, /"sourceEdit"/);
  assert.match(host, /sourceEditResult/);
  assert.match(designer, /status: "applied" \| "noop" \| "conflict" \| "failed"/);
  assert.match(designer, /requestId: id, source: payload\.source/);
  assert.match(designer, /sourceTimer = undefined/);
  assert.match(designer, /generation <= lastModelGeneration/);
  assert.match(designer, /nodePath: number\[\]/);
  assert.match(designer, /instancePath/);
  assert.match(designer, /if \(!left\?\.instancePath\) return true/);
  assert.match(designer, /return left\.instancePath === right\?\.instancePath/);
  assert.match(designer, /function scheduleOptimisticPreview/);
  assert.match(designer, /requestAnimationFrame/);
  assert.match(designer, /pendingSourceEdits\.push/);
  assert.match(designer, /queueMicrotask\(pumpDocumentWork\)/);
  assert.match(designer, /draw\(false\)/);
  assert.match(host, /let cachedComponents: CatalogBundle \| undefined/);
  assert.match(host, /event\.document\.uri\.toString\(\) !== document\.uri\.toString\(\)/);
  assert.doesNotMatch(host, /id="preview-label"/);
  assert.doesNotMatch(designer, /function previewValues/);
  assert.doesNotMatch(designer, /byId<HTMLSelectElement>\("preview"\)/);
  assert.match(host, /WorkspaceEdit/);
  assert.match(host, /"saveSource"/);
  assert.match(host, /targetDocument\.save\(\)/);
  assert.match(host, /toProtocolText\(document\.getText\(\)\)/);
  assert.match(host, /fromProtocolText\(requested, document\.eol === vscode\.EndOfLine\.CRLF/);
  assert.match(host, /committed\.kind === "mismatch"/);
  assert.doesNotMatch(host, /onWillSaveTextDocument/);
  assert.doesNotMatch(host, /const changed = new Promise<SourcePayload>/);
  assert.match(designer, /key: "Mod-s", preventDefault: true, run: requestSave/);
  assert.match(designer, /function pumpDocumentWork/);
  assert.match(designer, /源码写入超时，已解除锁定/);
  assert.match(designer, /属性写入超时，已解除锁定/);
  assert.doesNotMatch(html, /source-breadcrumb|source-status/);
  assert.match(designer, /function setupOutlineDivider/);
  assert.match(designer, /function setupArtboardViewport/);
  assert.match(designer, /spacePanHeld/);
  assert.doesNotMatch(host, /id="control-constraints"/);
  assert.doesNotMatch(designer, /controlAvailableWidth|controlAvailableHeight/);
  assert.match(designer, /canvas\.style\.width = isPage \? `\$\{width\}px` : "max-content"/);
  assert.match(designer, /byId\("device-label"\)\.hidden = !isPage/);
  assert.match(css, /#design-workbench > main \{ grid-column: 3; min-width: 0; overflow: hidden;/);
  assert.match(css, /#inspector \{ grid-column: 4;/);
  assert.doesNotMatch(host, /id="left-tabs"/);
  assert.doesNotMatch(host, /id="toolbox"/);
  assert.doesNotMatch(designer, /data-left-tab/);
  assert.match(designer, /Imported implementations are/);
  assert.match(designer, /componentTemplate\(node\)\) row\.ondblclick/);
  assert.doesNotMatch(designer, /outline\(child, host, depth \+ 1, \[\.\.\.trace/);
});

test("the inspector exposes only applicable Chinese controls and preserves the Lua boundary", async () => {
  const host = await readFile("src/extension.ts", "utf8");
  const designer = await readFile("src/webview/designer.ts", "utf8");
  const css = await readFile("media/preview.css", "utf8");
  const vocabulary = await readFile("packages/spec/src/vocabulary.ts", "utf8");
  assert.match(designer, /key !== "x:Ref"/);
  assert.match(designer, /definition\?\.kind === "enum"/);
  assert.match(designer, /function layoutResult/);
  assert.match(designer, /closeCompletion\(update\.view\)/);
  assert.match(designer, /closeOnBlur:\s*true/);
  assert.match(designer, /function applyChildLayout/);
  assert.match(designer, /ChildLayout/);
  assert.match(vocabulary, /"容器": "Container"/);
  assert.match(vocabulary, /ChildLayout/);
  assert.match(vocabulary, /"插槽名": "Name"/);
  assert.match(vocabulary, /"原生菜单安全区": "NativeMenuInset"/);
  assert.match(designer, /tagLabel\.textContent = "标签类型"/);
  assert.doesNotMatch(designer, /标签类型（可搜索）/);
  assert.match(designer, /const visible = \["全部", \.\.\.\[\.\.\.new Set\(choices\.map\(tagCategory\)\)\]\];/);
  assert.match(designer, /\$\{alias\}:\$\{component\}/);
  assert.match(designer, /const categoryLabel =/);
  assert.doesNotMatch(designer, /已导入组件/);
  assert.match(css, /\.binding-options \{ display: grid; gap: 10px;/);
  assert.match(designer, /category\.value = visible\.includes\(current\) \? current : "全部"/);
  assert.match(designer, /definition\?\.ui/);
  assert.match(host, /const seenMarkup = new Set<string>\(\)/);
  assert.match(host, /\[\$\{luaString\(item\.name\)\}\] =/);
  assert.match(designer, /type DesignerEdit = \{ id: number; type: "setAttribute" \| "resetAttribute" \| "setTag"; source: string; start: number; path\?: number\[\]/);
  assert.match(designer, /sourceHasUncommittedDraft/);
  assert.match(designer, /path: nodePath\(node\)/);
  assert.match(designer, /glyph: "↥", rotation: -90/);
  assert.match(designer, /glyph: "↔", rotation: 90/);
  assert.match(designer, /glyph: "↹", rotation: 90/);
  assert.match(designer, /"VerticalAlignment", "HorizontalAlignment"/);
  assert.match(host, /designerEditResult/);
  assert.match(host, /replaceDocumentText/);
  assert.doesNotMatch(designer, /canonicalTag\(node\.tag\) === "lui:Page" && key === "Margin"/);
  assert.match(designer, /editNode\(node, "resetAttribute"/);
  assert.match(css, /\.alignment-arrow \{[^}]*rotate\(var\(--alignment-arrow-rotation/);
  assert.doesNotMatch(css, /\.alignment-icon\.horizontal-left/);
  assert.doesNotMatch(css, /\.alignment-icon\.vertical-top/);
});

test("the preview implements DockPanel, reverse flow, transform fields and the control host", async () => {
  const designer = await readFile("src/webview/designer.ts", "utf8");
  const css = await readFile("media/preview.css", "utf8");
  const vocabulary = await readFile("packages/spec/src/vocabulary.ts", "utf8");
  assert.match(designer, /function arrangeDockPanel/);
  assert.match(designer, /attrs\.FlowDirection === "从右到左" \? "row-reverse"/);
  assert.match(designer, /function cssTransform/);
  assert.match(designer, /RenderTransformOrigin/);
  assert.match(designer, /availableWidth: number; availableHeight: number;\s*desiredWidth: number; desiredHeight: number;/);
  assert.match(designer, /box-model-position/);
  assert.match(designer, /box-model-margin/);
  assert.match(designer, /box-model-boundary/);
  assert.match(designer, /box-model-padding/);
  assert.match(designer, /contentWidth: Math\.max\(0, Math\.round\(\(width - padding\.left/);
  assert.match(css, /#canvas\.control-preview/);
  assert.match(vocabulary, /"渲染变换": "RenderTransform"/);
  assert.match(vocabulary, /"布局变换": "LayoutTransform"/);
});

test("the preview selects the deepest visual LUI node and composite buttons keep their children", async () => {
  const designer = await readFile("src/webview/designer.ts", "utf8");
  const runtime = await readFile("packages/runtime-urhox-lua/adapter/Runtime.lua", "utf8");
  assert.match(designer, /function pickVisualTarget/);
  assert.match(designer, /event\.composedPath\(\)/);
  assert.match(designer, /byId\("canvas"\)\.addEventListener\("click", pickVisualTarget\)/);
  assert.doesNotMatch(designer, /wrapper\.addEventListener\("click", \(event\) => \{ event\.stopImmediatePropagation\(\); pick\(node\); \}, true\)/);
  assert.match(runtime, /local function configureVisualHost/);
  assert.match(runtime, /if #children > 0 then props\.text = text ~= nil and tostring\(text\) or ""/);
  assert.match(runtime, /appendChildren\(widget, children\)/);
});

test("the preview defaults to the Maker long-screen viewport and hides unresolved conditional branches", async () => {
  const manifest = await readFile("package.json", "utf8");
  const host = await readFile("src/extension.ts", "utf8");
  const designer = await readFile("src/webview/designer.ts", "utf8");
  const css = await readFile("media/preview.css", "utf8");
  assert.match(manifest, /"default": "390x844"/);
  assert.match(host, /get<string>\("preview\.defaultDevice", "390x844"\)/);
  assert.doesNotMatch(designer, /return samples\[path\];|towerText: "继续爬塔"/);
  assert.match(designer, /resolvePreviewAttributes\(node,scope,attributeKey\)/);
  const snapshot=await readFile('src/webview/previewSnapshot.ts','utf8');
  assert.match(snapshot,/key==='Visibility'&&binding&&attrs\[key\]===undefined/);
  assert.doesNotMatch(designer, /autoFitArtboard/);
  assert.doesNotMatch(designer, /new ResizeObserver\(resize\)\.observe\(stage\)/);
  assert.match(designer, /function fitArtboard\(\): void \{ fitArtboardToStage\(\); \}/);
  assert.match(css, /#artboard \{ position: relative;/);
  assert.match(css, /#canvas \{ position: absolute;[^}]*width: 390px;[^}]*padding: 0;/);
  assert.match(css, /\.lui-node\.safe-area \{ padding: 0; border: 0;/);
});
